DuDu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import dudu.urls as dudu

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(dudu, namespace='dudu')),
]

dudu/urls.py
from django.conf.urls import url
from .views import index, add_message

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-message/$', add_message, name='add-message'),
]

dudu/models.py
from django.db import models


class Message(models.Model):
    sender = models.CharField(max_length=27)
    receiver = models.CharField(max_length=27)
    text = models.TextField(max_length=140)
    isFeatured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender + ' to ' + self.receiver + ' - Message ' + str(self.pk)

dudu/views.py
import datetime
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *

response = {}


def index(request):
    if (not Message.objects.all()):
        Message.objects.create(sender="Arga Ghulam Ahmad", receiver="You", text="Hello, World!", isFeatured=True)

    response['featured'] = Message.objects.filter(isFeatured=True)[0]
    response['messages'] = list(reversed(Message.objects.all()))
    return render(request, 'base.html', response)


@csrf_exempt
def add_message(request):
    if request.method == 'POST':
        sender = request.POST['sender']
        receiver = request.POST['receiver']
        message = request.POST['message']
        obj_message = Message(sender=sender, receiver=receiver, text=message)
        obj_message.save()

        str_datetime = (datetime.datetime.now().strftime('%b. %d, %Y, %-I:%M %p'))
        if (str_datetime[len(str_datetime) - 2:] == 'AM'):
            str_datetime = str_datetime[:len(str_datetime) - 2] + 'a.m.'
        elif (str_datetime[len(str_datetime) - 2:] == 'PM'):
            str_datetime = str_datetime[:len(str_datetime) - 2] + 'p.m.'
        return JsonResponse({'status': 'success', 'date_time': str_datetime})
    else:
        return JsonResponse({'status': 'failed'})

dudu/templates/base.html
{% load staticfiles %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% comment %}<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="icon" href="{% static 'img/dudu.ico' %}" type="image/x-icon" />{% endcomment %}
    <link rel="icon" href="https://bytebucket.org/argaghulamahmad/image-hosting/raw/b5d13302a22f761ed2ce15dd4b85965dfb6dcafa/dudu/dudu.ico" type="image/x-icon"/>
    <style>
        @media (max-width: 430px) {
            #form-card {
                width: 330px;
                margin-top: 20px;
            }
        }

        /* // Extra small devices (portrait phones, less than 576px) */

        @media (max-width: 575px) {
            #web-title {
                text-align: center;
            }

            #web-subtitle {
                text-align: center;
                display: none;
            }

            #logo {
                width: 100%;
                margin-left: auto;
                margin-right: auto;
            }

            #sub-logo {
                display: none;
            }
        }

        /* // Small devices (landscape phones, 576px and up) */

        @media (min-width: 576px) and (max-width: 767px) {
        }

        /* // Medium devices (tablets, 768px and up) */

        @media (min-width: 768px) and (max-width: 991px) {
        }

        /* // Large devices (desktops, 992px and up) */

        @media (min-width: 992px) and (max-width: 1199px) {
        }

        /* // Extra large devices (large desktops, 1200px and up) */

        @media (min-width: 1200px) {
        }

        #main-container {
            padding: 20px;
        }

        div #featured-area {
            padding: 30px;
        }

        #sendmessage-form {
            padding: 20px;
        }

        div .border-gap {
            padding: 30px;
        }

        div .bottom-gap {
            padding-bottom: 35px;
        }

        #submit-button {
            float: right;
        }

        #header-subtitle {
            padding-top: 7px;
            text-align: right;
            padding-top: 25px;
        }

        #web-title {
            display: none;
        }

        #web-subtitle {
            display: none;
        }
    </style>
</head>

<body>
<div id="main-container" class="container">
    <div class="row no-gutters">
        <div class="col-12 col-sm-6 col-md-8">
            <h1 id="web-title">Dari Untuk</h1>
            {% comment %}<img id="logo" src="{% static 'img/DariUntuk.png' %}" alt="">{% endcomment %}
            <img id="logo" src="https://bitbucket.org/argaghulamahmad/image-hosting/raw/b5d13302a22f761ed2ce15dd4b85965dfb6dcafa/dudu/DariUntuk.png" alt="">
        </div>
        <div class="col-6 col-md-4" id="header-subtitle">
            <h2 id="web-subtitle">Kirim pesan jadi mudah</h2>
            <a href="https://github.com/ArgaLabs">
                {% comment %}<img id="sub-logo" href="https://github.com/ArgaLabs" src="{% static 'img/ArgaLabs.png' %}"
                     alt="">
                {% endcomment %}
                <img id="sub-logo" href="https://github.com/ArgaLabs" src="https://bitbucket.org/argaghulamahmad/image-hosting/raw/b5d13302a22f761ed2ce15dd4b85965dfb6dcafa/dudu/ArgaLabs.png"
                     alt="">
            </a>
        </div>
    </div>
    <div id="featured-area">
        <div class="card text-center card-outline-info">
            <div class="card-header">
                Featured Message
            </div>
            {% if featured %}
                <div class="card-block">
                    <h4 class="card-title">from: {{ featured.sender }}, to: {{ featured.receiver }}.</h4>
                    <p class="card-text">{{ featured.text }}</p>
                </div>
                <div class="card-footer text-muted">
                    {{ featured.created_at }}
                </div>
            {% else %}
                <div class="alert alert-danger text-center">
                    <strong>There is'nt message!</strong>
                </div>
            {% endif %}
        </div>
        <br>
        <div class="row">
            <div class="col col-md-8">
                <div class="card card-outline-primary">
                    <h4 class="card-header">Messages</h4>
                    <div id="messages-area" class="card-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="card border-gap">
                                    <div class="card-body">
                                        <h4 class="card-title">from: {{ message.sender }}, to: {{ message.receiver }}.</h4>
                                        <p class="card-text">{{ message.text }}</p>
                                    </div>
                                    <br>
                                    <footer>{{ message.created_at }}</footer>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>There is'nt message!</strong>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4">
                <div id="form-card" class="card card-outline-success">
                    <div class="card-header">
                        <h4>Send a message</h4>
                    </div>
                    <div class="card-body">
                        <div id="sendmessage-form">
                            <div class="form-group">
                                <label>From</label>
                                <input id="sender" class="form-control" type="text">
                            </div>
                            <div class="form-group">
                                <label>To</label>
                                <input id="receiver" class="form-control" type="text">
                            </div>
                            <div class="form-group">
                                <label for="exampleTextarea">Message</label>
                                <textarea id="message" class="form-control" id="exampleTextarea" rows="3"></textarea>
                            </div>
                            <div class="bottom-gap">
                                <label class="form-check-label">
                                    <input id="agree-checkbox" class="form-check-input" type="checkbox"> I agree with
                                    the terms and
                                    conditions.
                                </label>
                                <br>
                                <div>
                                    <button type="submit" id="submit-button" class="btn btn-primary right">Submit
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block footer %}
        {% include "partials/footer.html" %}
    {% endblock %}
</div>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#submit-button").click(function () {
            var receiver = $("#receiver").val();
            var sender = $("#sender").val();
            var message = $("#message").val();
            var is_checked = document.getElementById('agree-checkbox').checked;

            console.log(receiver + ' to ' + sender);
            console.log('Message: ' + message);
            console.log(is_checked);

            if (receiver !== '' && sender !== '') {
                if (message !== '') {
                    if (is_checked) {
                        addMessage(sender, receiver, message)
                    } else {
                        alert("You must agree terms and condition!")
                    }
                } else {
                    alert("Message field must be filled!")
                }
            } else {
                alert("You must fill 'from' and 'to' field!")
            }
        });

        var addMessage = function (sender, receiver, message) {
            $.ajax({
                method: "POST",
                url: "{% url "dudu:add-message" %}",
                data: {sender: sender, receiver: receiver, message: message},
                success: function (data) {
                    if (data.status === 'success') {
                        console.log(data.status);
                        var message_area = $("#messages-area");
                        var messages = message_area.html();
                        var date_time = data.date_time;

                        var script = 'script>';

                        if (message.indexOf(script) !== -1) {
                            location.reload();
                        } else {
                            message_area.html(
                                "<div class=\"card border-gap\">" +
                                "<div class=\"card-body\">" +
                                "<h4 class=\"card-title\">from: " + sender + ", to: " + receiver + ".</h4>" +
                                "<p class=\"card-text\">" + message + "</p>" +
                                "</div>" +
                                "<br>" +
                                "<footer>" + date_time + "</footer>" +
                                "</div>" + messages
                            )
                        }
                    } else {
                        console.log(data.status);
                    }
                },
                error: function (error) {
                    alert(error.responseText)
                }
            });
        };
    });
</script>
</body>

</html>

dudu/templates/partials/footer.html
<div class="container text-center">
    <p>Arga Ghulam Ahmad © 2018</p>
</div>